[project]
name = "agent03"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "beautifulsoup4>=4.15.0",
    "chromadb",
    "fastapi>=0.141.1",
    "langchain>=1.4.0",
    "langchain-chroma>=1.1.0",
    "langchain-community>=0.4.2",
    "langchain-deepseek>=1.1.0",
    "langchain-huggingface>=1.2.2",
    "langgraph>=1.2.11",
    "langgraph-checkpoint>=4.2.0",
    "pydantic>=2.13.5",
    "python-dotenv>=1.2.3",
    "pyyaml>=6.0.3",
    "rank-bm25",
    "requests>=2.34.2",
    "sentence-transformers>=6.0.1",
    "uvicorn>=0.52.4",
]
[[tool.uv.index]]
url = "https://pypi.tuna.tsinghua.edu.cn/simple"
default = true

[dependency-groups]
dev = [
    "ipython>=9.17.1",
]

